#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries. simply type the 
# menu entries you want to add after this comment. 
# NOTE: Be careful not to change the `exec tail` line above.

# Menu Entry for Shutdown
menuentry "Shutdown" {
	echo "System shutting down..."
	halt
}

# Menu Entry for Reboot
menuentry "Reboot" {
	echo "System rebooting..."
	reboot
}
