#!/usr/bin/env bash

# NOTE: RUN ALL THE BELOW COMMANDS ENCLOSED INSIDE -c in zsh (I.E. SINGLE LINE COMMAND) USING wezterm --start -- zsh -c " "
# NOTE: start of the command
wezterm start -- zsh -c '

# NOTE: If the backslash appears at the end of a line (with no characters, including no spaces, after it), it tells the shell to ignore the newline character that follows, effectively continuing the command onto the next line. 
# NOTE: ; => used to perform command chaining in tmux, \; => used to escape the ; character

# Create a session for all the different configs 
tmux new -d -s Configs -n NvimConfigs "nvim ~/.config/nvim/" \; \
    neww -n HyprConfigs "nvim ~/.config/hypr/" \;  \
    neww -n TmuxConfigs "nvim ~/.config/tmux/" \; \
    neww -n WeztermConfigs "nvim ~/.config/wezterm/";

# Create a session for the Next.js project 
tmux new -d -s next\.js -n nextApp "nvim /mnt/Aayush/WEB/NEXT.JS/" \; \
    neww -n ForServer \; \
    send-keys "cd /mnt/Aayush/WEB/NEXT.JS/ && clear" Enter \;

# Attach to the `configs` session 
tmux a -t Configs \; \
select-window -t 1 \; \
neww \; send-keys "hyprctl dispatch movetoworkspacesilent 3 && exit" Enter \;
'

# NOTE: The below line creates a new window and executes the command in zsh , because the focus is captured by the tmux due to attaching, so running commands outside of tmux is not possible 
