# Run Equibop in Wayland 
--ozone-platform=wayland

# Start Equibop minimized
--start-minimized

# Disable Chromium from adjusting mic. volume automatically
--disable-features=WebRtcAllowInputVolumeAdjustment
