# l -> locked, will also work when an input inhibitor (e.g. a lockscreen) is active.
# r -> release, will trigger on release of a key.
# o -> longPress, will trigger on long press of a key.
# e -> repeat, will repeat when held.
# n -> non-consuming, key/mouse events will be passed to the active window in addition to triggering the dispatcher.
# m -> mouse, see below.
# t -> transparent, cannot be shadowed by other binds.
# i -> ignore mods, will ignore modifiers.
# s -> separate, will arbitrarily combine keys between each mod/key, see [Keysym combos](#keysym-combos) above.
# d -> has description, will allow you to write a description for your bind.
# p -> bypasses the app's requests to inhibit keybinds.
# u -> bypass submap, triggers even if a submap is active.

$mainMod = SUPER
$HYPRSCRIPTS = ~/.config/hypr/scripts
$terminal = ghostty +new-window
$emojiPicker = rofimoji
$fileManager = yazi
$browser = zen-browser

# KILL Hyprland
bind = CTRL ALT , DELETE , exec, killall Hyprland || pkill Hyprland 

# Applications
bind = $mainMod, RETURN, exec, $terminal # Open the terminal
bindr = $mainMod, O, exec, $browser # Open the browser
bindr = $mainMod SHIFT, O, exec, $browser --blank-window # Open blank browser window
bind = $mainMod, E, exec, $terminal start -- $fileManager # Open the filemanager
bind = $mainMod, I, exec, $emojiPicker # Open the emoji picker

# Windows
bind = $mainMod, Q, killactive # Kill active window
bind = $mainMod SHIFT, Q, forcekillactive # Force kill active window
bind = $mainMod, F, fullscreen, 0 # Set active window to fullscreen
bind = $mainMod, M, fullscreen, 1 # Maximize Window
bind = $mainMod, T, togglefloating # Toggle active windows into floating mode
bind = $mainMod SHIFT, T, workspaceopt, allfloat # Toggle all windows into floating mode

# bind = ALT, J, togglesplit # Toggle splitwindow mode


bindm = $mainMod, mouse:272, movewindow # Move window with the mouse
bindm = $mainMod, mouse:273, resizewindow # Resize window with the mouse

bind = $mainMod, G, togglegroup # Toggle window group

# Actions
bind = $mainMod SHIFT, A , exec, ~/.config/hypr/scripts/toggleAnimations.sh # Toggle animations
bind = $mainMod , SPACE , exec, pkill rofi || rofi -show drun # Open rofi-wayland launcher in drun mode (`pkill rofi` so that repressing the keybind kills the exisitng rofi launcher popup)
bind = $mainMod , C , exec, pkill rofi || rofi -show run # Open rofi launcher in run mode


bind = $mainMod SHIFT, B, exec,~/.config/hypr/scripts/reloadWaybar.sh # Reload waybar
bind = $mainMod CTRL, B, exec, ~/.config/hypr/scripts/toggleWaybar.sh # Toggle waybar

bind = $mainMod SHIFT, R, exec,hyprctl reload &&  notify-send "Reloaded Hyprland Config" # Reload hyprland config

bind = $mainMod, V, exec, cliphist list | rofi -dmenu | cliphist decode | wl-copy # Open clipboard manager
bind = $mainMod SHIFT, V, exec, cliphist list | rofi -dmenu | cliphist delete # Delete a custom entry from the clipboard manager

# Move the Focus
bind = $mainMod, h, movefocus, l # Move focus left
bind = $mainMod, l, movefocus, r # Move focus right
bind = $mainMod, k ,movefocus, u # Move focus up
bind = $mainMod, j, movefocus, d # Move focus down


# to move window
bind = $mainMod CTRL,K, movewindow, u
bind = $mainMod CTRL,J, movewindow, d
bind = $mainMod CTRL,H, swapnext, left  # Swap with the window above
bind = $mainMod CTRL,L, swapnext, right  # Swap with the window below

#The key up event that is sent after you hit enter to execute dpms off turns the dpms back on. So sleep 1 && hyprctl dispatch ... ensures that the key event is not passed to the hyprctl dispatch .. right after executing the command turning the monitor back on 
bindl = ALT, L, exec, ~/.config/hypr/scripts/lockscreen.sh # Display the lock screen using hyprlock
bind = ALT, M , exec , wlogout -s #Display the wlogout menu along with keybindings(-s flag)

bindl =  ALT, S ,exec, ~/.config/hypr/scripts/suspend.sh
bindl = CTRL ALT , DELETE, exec, hyprctl dispatch exit
