[ids]
*

[global]
chord_timeout=200

[main]
capslock=overload(control,esc)
esc=capslock

# Toggle `vim-mode` layer with right alt key
rightcontrol=toggle(vim-mode) 

# Keybind to activate layered `vim-mode` layer with leftshift+leftalt
leftshift+leftalt=layer(vim-mode)

# vim-mode layer
[vim-mode] 

h=left
j=down
k=up
l=right
esc=esc
