[ids]
*

[global]
chord_timeout=100

[main]
rightcontrol=rightcontrol
righthshift=rightshift

capslock=overload(control,esc)
esc=capslock

# Keybind to activate layered `vim-mode` layer with leftshift+leftalt
leftshift+leftalt=layer(vim-mode)

# vim-mode layer
[vim-mode] 

h=left
j=down
k=up
l=right
esc=esc
