# [[shades]]
# name = "vibrance"
# default = true

[[shades]]
name = "blue-light-filter-75"
start_time = 19:30:00
end_time = 06:00:00

# [[shades]]
# name = "color-filter"
# [shades.config]
# type = "red-green" # "red-green", "green-red", "blue-yellow"
# strength = 1.0     # 0.0 - 1.0
