hl.workspace_rule({ workspace = '1', monitor = 'eDP-1', default = true, persistent = true })
hl.workspace_rule({ workspace = '2', monitor = 'eDP-1' })
hl.workspace_rule({ workspace = '3', monitor = 'eDP-1' })
hl.workspace_rule({ workspace = '4', monitor = 'eDP-1' })
hl.workspace_rule({ workspace = '5', monitor = 'eDP-1' })
hl.workspace_rule({ workspace = '6', monitor = 'eDP-1' })
hl.workspace_rule({ workspace = '7', monitor = 'eDP-1' })
hl.workspace_rule({ workspace = '8', monitor = 'eDP-1' })
hl.workspace_rule({ workspace = '9', monitor = 'eDP-1' })
hl.workspace_rule({ workspace = '10', monitor = 'eDP-1' })

hl.workspace_rule({ workspace = '11', monitor = 'HDMI-A-1', default = true })
hl.workspace_rule({ workspace = '12', monitor = 'HDMI-A-1' })
hl.workspace_rule({ workspace = '13', monitor = 'HDMI-A-1' })
hl.workspace_rule({ workspace = '14', monitor = 'HDMI-A-1' })
hl.workspace_rule({ workspace = '15', monitor = 'HDMI-A-1' })
hl.workspace_rule({ workspace = '16', monitor = 'HDMI-A-1' })
hl.workspace_rule({ workspace = '17', monitor = 'HDMI-A-1' })
hl.workspace_rule({ workspace = '18', monitor = 'HDMI-A-1' })
hl.workspace_rule({ workspace = '19', monitor = 'HDMI-A-1' })
hl.workspace_rule({ workspace = '20', monitor = 'HDMI-A-1' })

--  For smart gaps (i.e. no gaps when only one tiled window or floating window is present)
hl.workspace_rule({ workspace = 'w[t1]', gaps_out = 0, gaps_in = 0 }) -- for a workspace containing only 1 tiled window, set gapsout and gapsin to 0
hl.workspace_rule({ workspace = 'f[1]', gaps_out = 0, gaps_in = 0 })  -- for a fullscreen state of workspace equal to 1 , set gapsout and gapsin to 0:w
hl.window_rule({ match = { workspace = 'w[t1]', float = 0 }, border_size = 0 })
hl.window_rule({ match = { workspace = 'w[t1]', float = 0 }, rounding = 0 })
hl.window_rule({ match = { workspace = 'f[1]', float = 0 }, border_size = 0 })
hl.window_rule({ match = { workspace = 'f[1]', float = 0 }, rounding = 0 })
