#    ___       __           __           __ 
#   / _ |__ __/ /____  ___ / /____ _____/ /_
#  / __ / // / __/ _ \(_-</ __/ _ `/ __/ __/
# /_/ |_\_,_/\__/\___/___/\__/\_,_/_/  \__/ 
#                                           

# Using waypaper(wallpaper setter) and awww(wayland wallpaper daemon)
exec-once = awww-daemon

# Startup waybar on startup
exec-once=  waybar

# Udiskie
exec-once= udiskie

# Load Notification Daemon
exec-once = swaync  

exec-once = hyprsunset
exec-once = hypridle


# Load cliphist history
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data

exec-once = [workspace 11 silent] discord

# Execute the tmux script
exec-once = ~/.config/hypr/scripts/tmuxSetup

# Nm-Applet
exec-once = nm-applet

# Load the nepali date
exec-once = ~/sysScripts/fetchNepaliDate.sh
